"""
InterestDomainMatcher — checks if a domain matches any interest keyword.

is_interest_domain(domain: str) -> bool
    True if domain matches or is subdomain of any interest domain.

get_interest_domains() -> set[str]
    Returns all domains derived from interest keywords.
"""
import logging
from urllib.parse import urlparse

from core.graph_interests import extract_interests

_logger = logging.getLogger(__name__)

# Hardcoded topic → domain inference map for common topics
_TOPIC_TO_DOMAIN = {
    "pytorch": "pytorch.org",
    "torch": "pytorch.org",
    "tensorflow": "tensorflow.org",
    "keras": "keras.io",
    "jax": "github.com/google/jax",
    "huggingface": "huggingface.co",
    "openai": "openai.com",
    "anthropic": "anthropic.com",
    "mistral": "mistral.ai",
    "llama": "llama.meta.com",
    "arxiv": "arxiv.org",
    "github": "github.com",
    "gitlab": "gitlab.com",
    "pypi": "pypi.org",
    "npm": "npmjs.com",
    "docker": "docker.com",
    "kubernetes": "kubernetes.io",
    "k8s": "kubernetes.io",
    "aws": "aws.amazon.com",
    "gcp": "cloud.google.com",
    "azure": "azure.microsoft.com",
    "heroku": "heroku.com",
    "railway": "railway.app",
    "vercel": "vercel.com",
    "netlify": "netlify.com",
    "cloudflare": "cloudflare.com",
    "fastapi": "fastapi.tiangolo.com",
    "flask": "flask.palletsprojects.com",
    "django": "djangoproject.com",
    "rails": "rubyonrails.org",
    "spring": "spring.io",
    "nodejs": "nodejs.org",
    "deno": "deno.land",
    "bun": "bun.sh",
    "rust": "rust-lang.org",
    "go": "go.dev",
    "golang": "go.dev",
    "c++": "isocpp.org",
    "cpp": "isocpp.org",
    "python": "python.org",
    "javascript": "javascript.info",
    "typescript": "typescriptlang.org",
    "react": "react.dev",
    "vue": "vuejs.org",
    "svelte": "svelte.dev",
    "angular": "angular.io",
    "nextjs": "nextjs.org",
    "next.js": "nextjs.org",
    "solidjs": "solidjs.com",
    "astro": "astro.build",
    "tailwind": "tailwindcss.com",
    "webpack": "webpack.js.org",
    "vite": "vitejs.dev",
    "esbuild": "esbuild.github.io",
    "deno": "deno.land",
    "bun": "bun.sh",
    "postgres": "postgresql.org",
    "postgresql": "postgresql.org",
    "mysql": "mysql.com",
    "mongodb": "mongodb.com",
    "redis": "redis.io",
    "sqlite": "sqlite.org",
    "prisma": "prisma.io",
    "sequelize": "sequelize.org",
    "sqlalchemy": "sqlalchemy.org",
    "elasticsearch": "elastic.co",
    "opensearch": "opensearch.org",
    "kibana": "elastic.co",
    "grafana": "grafana.com",
    "prometheus": "prometheus.io",
    "jenkins": "jenkins.io",
    "githubactions": "github.com/features/actions",
    "circleci": "circleci.com",
    "travis": "travis-ci.org",
    "sentry": "sentry.io",
    "datadog": "datadoghq.com",
    "newrelic": "newrelic.com",
    "cloudwatch": "aws.amazon.com/cloudwatch",
    "terraform": "terraform.io",
    "ansible": "ansible.com",
    "puppet": "puppet.com",
    "helm": "helm.sh",
    "istio": "istio.io",
    "envoy": "envoyproxy.io",
    "linkerd": "linkerd.io",
    "consul": " consul.io",
    "vault": "vaultproject.io",
    "nomad": "nomadproject.io",
    "packer": "packer.io",
    "vagrant": "vagrantup.com",
    "virtualbox": "virtualbox.org",
    "vmware": "vmware.com",
    "docker": "docker.com",
    "containerd": "containerd.io",
    "kubernetes": "kubernetes.io",
    "k8s": "kubernetes.io",
    "helm": "helm.sh",
    "rook": "rook.io",
    "argocd": "argoproj.github.io/argo-cd",
    "flux": "fluxcd.io",
    "crossplane": "crossplane.io",
    "talos": "talos.dev",
    "flatcar": "flatcar-linux.org",
    "quay": "quay.io",
    "harbor": "goharbor.io",
    "dex": "dexidp.io",
    "oauth": "oauth.net",
    "oidc": "openid.net",
    "saml": "saml.xml",
    "ldap": "openldap.org",
    "keycloak": "keycloak.org",
    "auth0": "auth0.com",
    "okta": "okta.com",
    "ping": "pingidentity.com",
    "wguard": "wireguard.com",
    "openvpn": "openvpn.net",
    "tailscale": "tailscale.com",
    "nordvpn": "nordvpn.com",
    "cloudflare": "cloudflare.com",
    "fastly": "fastly.com",
    "akamai": "akamai.com",
    "cloudfront": "aws.amazon.com/cloudfront",
    "limetext": "limetext.github.io",
    "sqlitebrowser": "sqlitebrowser.org",
    "db Broswer": "sqlitebrowser.org",
    "dbeaver": "dbeaver.io",
    "tableplus": "tableplus.com",
    "datagrip": "jetbrains.com/datagrip",
    "pgadmin": "pgadmin.org",
    "adminer": "adminer.org",
    "phpmyadmin": "phpmyadmin.net",
    "couchdb": "couchdb.apache.org",
    "cassandra": "cassandra.apache.org",
    "couchbase": "couchbase.com",
    "dynamodb": "aws.amazon.com/dynamodb",
    "s3": "aws.amazon.com/s3",
    "gcs": "cloud.google.com/storage",
    "azureblob": "azure.microsoft.com/en-us/services/storage/blobs",
    "minio": "min.io",
    "r2": "cloudflare.com/r2",
    "snowflake": "snowflake.com",
    "bigquery": "cloud.google.com/bigquery",
    "redshift": "aws.amazon.com/redshift",
    "databricks": "databricks.com",
    "flink": "flink.apache.org",
    "spark": "spark.apache.org",
    "kafka": "kafka.apache.org",
    "pulsar": "pulsar.apache.org",
    "rabbitmq": "rabbitmq.com",
    "zeromq": "zeromq.org",
    "nats": "nats.io",
    "grpc": "grpc.io",
    "thrift": "thrift.apache.org",
    "avro": "avro.apache.org",
    "protobuf": "developers.google.com/protocol-buffers",
    "flatbuffers": "google.github.io/flatbuffers",
    "capnproto": "capnproto.org",
    "msgpack": "msgpack.org",
    "cbor": "cbor.io",
    "bson": "bsonspec.org",
    "json": "json.org",
    "xml": "w3.org/XML",
    "yaml": "yaml.org",
    "toml": "toml.io",
    "hcl": "terraform.io/docs/language",
    "jsonnet": "jsonnet.org",
    "cue": "cuelang.org",
    "dhall": "dhall-lang.org",
    "pkl": "pkl-lang.org",
    "templ": "templ.sh",
    "rizin": "rizin.re",
    "ghidra": "ghidra-sre.org",
    "ida": "hex-rays.com/ida",
    "binwalk": "github.com/ReFirmLabs/binwalk",
    "radare2": "rada.re",
    "frida": "frida.re",
    "lief": "lief.quarkslab.com",
    " capstone": "capstone-engine.org",
    "unicorn": "unicorn-engine.org",
    "qemu": "qemu.org",
    "bochs": "bochs.sourceforge.net",
    "simics": "intel.com/simics",
    "speakeasy": "github.com/trailofbits/speakeasy",
    "galois": "galoisinc.github.io/crucible",
    "kframework": "kframework.org",
    "mathexpr": "mathexpr.github.io",
    "symengine": "symengine.org",
    "sympy": "sympy.org",
    "mathematica": "wolfram.com/mathematica",
    "maple": "maplesoft.com/products/maple",
    "matlab": "mathworks.com/products/matlab",
    "octave": "gnu.org/software/octave",
    "julia": "julialang.org",
    "rstats": "r-project.org",
    "sagemath": "sagemath.org",
    "maxima": "maxima.sourceforge.net",
    "axiom": "axiom-developer.org",
    "fricas": "fricas.github.io",
    "reduce": "reduce-algebra.sourceforge.net",
    "yacas": "yacas.org",
    "mupad": "mupad.com",
    "cadabra": "cadabra.science",
    "tensorfow": "tensorflow.org",
    "jax": "github.com/google/jax",
    "pytorch": "pytorch.org",
    "mxnet": "mxnet.apache.org",
    "chainer": "chainer.org",
    "deeplearning4j": "deeplearning4j.org",
    "onnx": "onnx.ai",
    "tensorrt": "developer.nvidia.com/tensorrt",
    "openvino": "docs.openvino.ai",
    "tflite": "www.tensorflow.org/lite",
    "coreml": "developer.apple.com/documentation/coreml",
    "mlmodel": "developer.apple.com/documentation/coreml",
    "onnxml": "onnxml.ai",
    "scikitlearn": "scikit-learn.org",
    "sklearn": "scikit-learn.org",
    "scipy": "scipy.org",
    "numpy": "numpy.org",
    "pandas": "pandas.pydata.org",
    "polars": "pola.rs",
    "dask": "dask.org",
    "modin": "modin.readthedocs.io",
    "vaex": "vaex.io",
    "xarray": "xarray.dev",
    "netcdf": "unidata.ucar.edu/software/netcdf",
    "hdf5": "hdfgroup.org/solutions/hdf5",
    "parquet": "parquet.apache.org",
    "avro": "avro.apache.org",
    "orc": "orc.apache.org",
    "delta": "delta.io",
    "iceberg": "iceberg.apache.org",
    "hudi": "hudi.apache.org",
    "clickhouse": "clickhouse.com",
    "duckdb": "duckdb.org",
    "questdb": "questdb.io",
    "timescale": "timescale.com",
    "influxdb": "influxdata.com",
    "prometheus": "prometheus.io",
    "victoriametrics": "victoriametrics.com",
    "mimir": "grafana.com/oss/mimir",
    "thanos": "thanos.io",
    "cortext": "corectx.io",
    "atoti": "atoti.io",
    "observability": "opentelemetry.io",
    "opentelemetry": "opentelemetry.io",
    "telemetry": "opentelemetry.io",
    "otel": "opentelemetry.io",
    "jaeger": "jaegertracing.io",
    "zipkin": "zipkin.io",
    " Tempo": "grafana.com/docs/tempo/latest",
    "loki": "grafana.com/oss/loki",
    "s3": "aws.amazon.com/s3",
    "minio": "min.io",
    "r2": "cloudflare.com/r2",
    "gcs": "cloud.google.com/storage",
    "azureblob": "azure.microsoft.com/en-us/services/storage/blobs",
    "efs": "aws.amazon.com/efs",
    "fsx": "aws.amazon.com/fsx",
    "ebs": "aws.amazon.com/ebs",
    "s3fs": "s3fs.readthedocs.io",
    "gcsfuse": "cloud.google.com/docs/gcsfuse",
    "blobfuse": "github.com/Azure/azure-storage-fuse",
    " JuiceFS": "juicefs.com",
    "ceph": "ceph.io",
    "gluster": "gluster.org",
    "sheepdog": "sheepdog.github.io",
    "hdfs": "hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs",
    "webhdfs": "hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html",
    "alluxio": "alluxio.io",
    "chaos": "litsec.io/chaos",
    "chaoseng": "chaosengineering.io",
    "chaosmesh": "chaos-mesh.org",
    "toxiproxy": "github.com/Shopify/toxiproxy",
    "gremlify": "gremlify.github.io",
    "chaosblade": "chaosblade.io",
    "AWES": "aws.amazon.com/fis",
    "farget": "github.com/chaosblade-io/chaosblade",
    "p Fault": "fault.in",
    "chAP": "github.com/microsoft/chaos-toolkit",
    "prana": "prana-db.netlify.app",
    "yandex": "yandex.com",
    "baidu": "baidu.com",
    "tencent": "tencent.com",
    "aliyun": "aliyun.com",
    "huawei": "huawei.com",
    "cloudflare": "cloudflare.com",
    "fastly": "fastly.com",
    "akamai": "akamai.com",
    "limelight": "limelight.com",
    "cachefly": "cachefly.com",
    "stackpath": "stackpath.com",
    "cloudfront": "aws.amazon.com/cloudfront",
    "cloudvideo": "aws.amazon.com/cloudfront",
    "rtmp": "adobe.com/products/rtmp",
    "hls": "apple.com/streaming",
    "dash": "dashif.org",
    "webrtc": "webrtc.org",
    "srt": "srtalliance.org",
    "zixi": "zixi.org",
    "smpte": "smpte.org",
    "ffmpeg": "ffmpeg.org",
    "gstreamer": "gstreamer.freedesktop.org",
    "mediaconch": "mediaarea.net/mediaconch",
    "vlc": "videolan.org/vlc",
    "mpv": "mpv.io",
    "handbrake": "handbrake.fr",
    "x264": "x264.org",
    "x265": "x265.org",
    "vp8": "webmproject.org/vp8",
    "vp9": "webmproject.org/vp9",
    "av1": "aomedia.org/av1",
    "hevc": "mpeg.chiariglione.org/hevc",
    "h264": "itu.int/rec/H.264",
    "aac": "mpeg.chiariglione.org/aac",
    "mp3": "mp3.com",
    "ogg": "xiph.org/ogg",
    "opus": "opus-codec.org",
    "flac": "xiph.org/flac",
    "alac": "apple.com/m Lossless",
    "wav": "wav.io",
    "aiff": "aiff.com",
    "webm": "webmproject.org",
    "mkv": "matroska.org",
    "mp4": "mpeg.chiariglione.org",
    "mov": "apple.com/quicktime",
    "avi": "microsoft.com/en-us/windows/movemaker",
    "wmv": "microsoft.com/en-us/windows/movemaker",
    "flv": "adobe.com/products/flash",
    "swf": "adobe.com/products/flash",
    "3gp": "3gpp.org",
    "3g2": "3gpp.org",
    "webp": "developers.google.com/speed/webp",
    "avif": "aomediacodec.github.io/avif",
    "heif": "nokiatech.github.io/heif",
    "bpg": "bellard.org/bpg",
    "jp2": "jpeg.org/jpeg2000",
    "png": "pngformat.com",
    "gif": "gif.com",
    "tiff": "tiff.org",
    "bmp": "bmp.fandom.com",
    "ico": "icoformat.com",
    "svg": "w3.org/Graphics/SVG",
    "eps": "adobe.com/creativecloud/libraries/eps",
    "pdf": "adobe.com/pdf",
    "ps": "adobe.com/postscript",
    "word": "microsoft.com/microsoft-365/word",
    "excel": "microsoft.com/microsoft-365/excel",
    "ppt": "microsoft.com/microsoft-365/powerpoint",
    "doc": "microsoft.com/microsoft-365/word",
    "xls": "microsoft.com/microsoft-3 65/excel",
    "pptx": "microsoft.com/microsoft-365/powerpoint",
    "docx": "microsoft.com/microsoft-365/word",
    "odt": "openoffice.org/product Writer",
    "ods": "openoffice.org/product Calc",
    "odp": "openoffice.org/product Impress",
    "rtf": "microsoft.com/windows/rtf",
    "tex": "tug.org/texmf",
    "latex": "latex-project.org",
    "markdown": "daringfireball.net/projects/markdown",
    "md": "daringfireball.net/projects/markdown",
    "rst": "docutils.sourceforge.net/rst.html",
    "asciidoc": "asciidoc.org",
    "textile": "textism.com/source/textile",
    "orgmode": "orgmode.org",
    "vim": "vim.org",
    "neovim": "neovim.io",
    "emacs": "gnu.org/software/emacs",
    "vscode": "code.visualstudio.com",
    "sublime": "sublimetext.com",
    "atom": "atom.io",
    "notepadpp": "notepad-plus-plus.org",
    "bbedit": "barebones.com/bbedit",
    "textmate": "macromates.com",
    "jetbrains": "jetbrains.com",
    "pycharm": "jetbrains.com/pycharm",
    "intellij": "jetbrains.com/idea",
    "webstorm": "jetbrains.com/webstorm",
    "goland": "jetbrains.com/goland",
    "clion": "jetbrains.com/clion",
    " rider": "jetbrains.com/rider",
    "datagrip": "jetbrains.com/datagrip",
    "fleet": "jetbrains.com/fleet",
    "zed": "zed.dev",
    "lapce": "lapce.dev",
    "helix": "helix-editor.com",
    "kakoune": "kakoune.org",
    "broot": "dystroy.org/broot",
    "xplr": "xplr.dev",
    "ranger": "github.com/ranger/ranger",
    "nnn": "github.com/jarun/nnn",
    "fzf": "github.com/junegunn/fzf",
    "fish": "fishshell.com",
    "zsh": "zsh.org",
    "bash": "gnu.org/software/bash",
    "sh": "pubs.opengroup.org/sh",
    "dash": "linux.die.net/man/1/dash",
    "posh": "github.com/PowerShell/PowerShell",
    "pwsh": "github.com/PowerShell/PowerShell",
    "powershell": "github.com/PowerShell/PowerShell",
    "cmd": "microsoft.com/windows/command-shell",
    "alacritty": "github.com/alacritty/alacritty",
    "kitty": "sw.kovidgoyal.net/kitty",
    "wezterm": "wezfurlong.org/wezterm",
    "tmux": "github.com/tmux/tmux",
    "screen": "gnu.org/software/screen",
    "byobu": "byobu.org",
    " multiplexer": "tmux.github.io",
    "ssh": "ssh.com",
    "openssh": "openssh.com",
    "putty": "putty.org",
    "bitvise": "bitvise.com",
    "mobaxterm": "mobaxterm.mobatek.net",
    "warp": " warp.dev",
    "terminus": "eugeny.github.io/terminus",
    "hyper": "hyper.is",
    "iterm2": "iterm2.com",
    "terminal": "microsoft.com/windows/terminal",
    "powershell": "github.com/PowerShell/PowerShell",
    "asciinema": "asciinema.org",
    "termrecord": "github.com/theonewolf/TermRecord",
    "script": "unix.org",
    "ttyrec": "0xcc.tuxfamily.org/ttyrec",
    "shell": "pubs.opengroup.org/sh",
    "zsh": "zsh.org",
    "fish": "fishshell.com",
    "bash": "gnu.org/software/bash",
    "ksh": "kornshell.com",
    "csh": "甲骨文.com/csh",
    "tcsh": "tcsh.org",
    "dash": "linux.die.net/man/1/dash",
    "ash": "linux.die.net/man/1/ash",
    "busybox": "busybox.net",
    "msys2": "msys2.org",
    "cygwin": "cygwin.com",
    "wsl": "docs.microsoft.com/windows/wsl",
    "wsl2": "docs.microsoft.com/windows/wsl",
    " subsystem": "docs.microsoft.com/windows/wsl",
    "windows": "microsoft.com/windows",
    "macos": "apple.com/macos",
    "linux": "linux.org",
    "ubuntu": "ubuntu.com",
    "debian": "debian.org",
    "fedora": "fedoraproject.org",
    "arch": "archlinux.org",
    "gentoo": "gentoo.org",
    "nixos": "nixos.org",
    "void": "voidlinux.org",
    "alpine": "alpinelinux.org",
    "rocky": "rockylinux.org",
    "almalinux": "almalinux.org",
    "oracle": "oracle.com/linux",
    "redhat": "redhat.com/rhel",
    "centos": "centos.org",
    "suse": "suse.com",
    "opensuse": "opensuse.org",
    "manjaro": "manjaro.org",
    "mint": "linuxmint.com",
    "pop": "system76.com/pop",
    "zorin": "zorin.com/os",
    "elementary": "elementary.io",
    "ende": "endeavouros.com",
    "garuda": "garudalinux.org",
    "archcraft": "archcraft.io",
    "arco": "arcolinux.com",
    "artix": "artixlinux.org",
    "postmarketos": "postmarketos.org",
    "mobian": "mobian-project.org",
    "pinephone": "pine64.org/pinephone",
    "librem": "puri.sm/products/librem-5",
    "sailfish": "sailfishos.org",
    "tizen": "tizen.org",
    "wearos": "android.com/wear",
    "watchos": "apple.com/watchos",
    "tvOS": "developer.apple.com/tvos",
    "ipados": "apple.com/ipados",
    "ios": "apple.com/ios",
    "ipad": "apple.com/ipad",
    "iphone": "apple.com/iphone",
    "android": "android.com",
    "chromium": "chromium.org",
    "chrome": "google.com/chrome",
    "firefox": "mozilla.org/firefox",
    "safari": "apple.com/safari",
    "edge": "microsoft.com/edge",
    "opera": "opera.com",
    "brave": "brave.com",
    "vivaldi": "vivaldi.com",
    "lynx": "lynx.invisible-island.net",
    "w3m": "w3m.sourceforge.net",
    "links": "artax.karl.mm Sturm",
    "elinks": "elinks.or.cz",
    "curl": "curl.se",
    "wget": "gnu.org/software/wget",
    "httrack": "httrack.com",
    "wireguard": "wireguard.com",
    "openvpn": "openvpn.net",
    "ipsec": "cisel.org/IPsec",
    "tls": "tls.io",
    "ssl": "globalsign.com/ssl",
    "https": "https://https.io",
    "http": "http://http.org",
    "dns": "dnsses.com",
    "dhcp": "isc.org/dhcp",
    "nat": "RFC 1631",
    "tcp": "rfc-editor.org/rfc/rfc793",
    "udp": "rfc-editor.org/rfc/rfc768",
    "icmp": "rfc-editor.org/rfc/rfc792",
    "ip": "rfc-editor.org/rfc/rfc791",
    "ipv4": "rfc-editor.org/rfc/rfc791",
    "ipv6": "rfc-editor.org/rfc/rfc8200",
    "arp": "tools.ietf.org/html/rfc826",
    "rarp": "tools.ietf.org/html/rfc903",
    "dns": "isc.org/dns",
    "mdns": "multicastdns.org",
    "llmnr": "tools.ietf.org/html/rfc6895",
    "sdn": "opennetworking.org/sdn",
    "nfv": "nfv.org",
    "mpls": "mefa.org/mpls",
    "bgp": "ietf.org/rfc/rfc4271",
    "ospf": "ietf.org/rfc/rfc2328",
    "isis": "ietf.org/rfc/rfc1195",
    "rip": "ietf.org/rfc/rfc2453",
    "eigrp": "cisco.com/c/en/us/td/docs/qos/techrefs/qoqos/qoqos_eigrp.html",
    "vrrp": "ietf.org/rfc/rfc5798",
    "hsrp": "cisco.com/c/en/us/products/collateral/ios-nx-os-technolo gy/enterprise-ip-communications/solution_lg_c22_448090.html",
    "glbp": "cisco.com/c/en/us/products/collateral/ios-nx-os-technolo gy/enterprise-ip-communications/solution_lg_c22_448090_ps6609_TSD_Products_Solution_Lg.html",
    "vlan": "ieee.org/standards/technologies/recognition",
    "vxlan": "rfc-editor.org/rfc/rfc7348",
    "geneve": "rfc-editor.org/rfc/rfc8926",
    "stt": "datatracker.ietf.org/doc/html/draft-ietf secvisage-sstc",
    "nvgre": "microsoft.com/windows-server/Networking/NVGRE",
    "qinq": "ietfreport.isoc.org/idref/rfc6340",
    "ppp": "rfc-editor.org/rfc/rfc1334",
    "pppoe": "rfc-editor.org/rfc/rfc2516",
    "slip": "rfc-editor.org/rfc/rfc1055",
    "framerelay": "atis.org/cgi-bin/framesig",
    "atm": "ietf.org/assignments",
    "sonet": "www. sonetsdn.com",
    "sdh": "itu.int/rec/T-REC-G",
    "otn": "itu.int/rec/T-REC-G",
    "mstp": " ieee.com/standards",
    "rstp": "ieee.org/standards",
    "stp": " ieee.org/stp",
    "spanningtree": "ieee.org/stp",
    "etherchannel": "cisco.com/c/en/us/td/docs/ios/lanswitch/configuration/guide/ls_ch ether chan",
    "lacp": "ieee.org/standards",
    "pagp": "cisco.com/c/en/us/td/docs/ios/lanswitch/configuration/guide/ls_ch ether chan",
    "vpc": "cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/vpc",
    "portchannel": "cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/vpc",
    "ethernet": "ieee.org/standards",
    "fib": "iacis.org/fib",
    "rib": "cumulusnetworks.com/lettuce",
    "asic": "asic.com",
    "fpga": "fpga.org",
    "gpu": "nvidia.com",
    "tpu": "cloud.google.com/tpu",
    "cpu": "intel.com",
    "arm": "arm.com",
    "riscv": "riscv.org",
    "mips": "mips.com",
    "x86": "intel.com",
    "x64": "amd.com",
    "ia64": "intel.com",
    "sparc": "oracle.com/sparc",
    "powerpc": "ibm.com/power",
    "avr": "microchip.com/avr",
    "msp430": "ti.com/msp430",
    "stm32": "st.com/stm32",
    "esp32": "espressif.com/esp32",
    "esp8266": "espressif.com/esp8266",
    "arduino": "arduino.cc",
    "raspberrypi": "raspberrypi.org",
    " BeagleBone": "beagleboard.org",
    "odroid": "hardkernel.com",
    "nanopi": "friendlyarm.com",
    "tinkerboard": "asus.com/tinkerboard",
    "rockchip": "rock-chips.com",
    "aml": "amlogic.com",
    "allwinner": "allwinnertech.com",
    "qualcomm": "qualcomm.com",
    "mediatek": "mediatek.com",
    "sdcard": "sdcard.org",
    "emmc": "jedec.org/standards/documents",
    "nand": "samsung.com",
    "nor": "intel.com/nor",
    "ssd": "samsung.com",
    "hdd": "wdc.com",
    "nvme": "nvmexpress.org",
    "sata": "sata-io.org",
    "pcie": "pcisig.com",
    "usb": "usb.org",
    "thunderbolt": "intel.com/thunderbolt",
    "bluetooth": "bluetooth.com",
    "ble": "bluetooth.com",
    "zigbee": "zigbee.org",
    "zwave": "zwaveassociation.com",
    "matter": "csa-iot.org/matter",
    "thread": "threadgroup.com",
    "wifi": "wi-fi.org",
    "802.11": "ieee.org/802.11",
    "wimax": "wimaxforum.org",
    "5g": "3gpp.org",
    "4g": "3gpp.org",
    "lte": "3gpp.org",
    "3g": "3gpp.org",
    "gsm": "gsm.org",
    "cdma": "3gpp2.org",
    "umts": "3gpp.org",
    "hsdpa": "3gpp.org",
    "hsupa": "3gpp.org",
    "hspa": "3gpp.org",
    "evdo": "qualcomm.com/evdo",
    "gsm": "gsm.org",
    "gprs": "gsmworld.com",
    "edge": "gsmassociation.com/edge",
    "imei": "gsmassociation.com/imei",
    "imsi": "gsmassociation.com/imsi",
    "sim": "gsmworld.com/sim",
    "usim": "3gpp.org",
    "esim": "gsma.com/esim",
    "rfid": "rfid.org",
    "nfc": "nfc-forum.org",
    "barcode": "barcordeliaiso",
    "qrcode": "qrcode.com",
    "datamatrix": "gsl.info.up Vish",
    "pdf417": "pdf417.pdf",
    "aztec": "取證影像壓縮",
    "maxicode": " USPS.com",
    "gps": "gps.gov",
    "gnss": "esa.int/gnss",
    "galileo": "esa.int/navigation",
    "glonass": "roscosmos.ru/glonass",
    "beidou": "beidou.gov.cn",
    "qzss": "qzss.go.jp",
    "irnss": "isro.gov.in/IRNSS",
    "navic": "isro.gov.in/navic",
    "sbas": "sbass.org",
    "waas": "faa.gov/go/waas",
    "egnos": "esa.int/egnos",
    "msas": "gaelle 日本",
    "sdrt": "rtcm不详",
    "dGPS": "ohdmas",
    "rtk": "rtklib.com",
    "ppk": "propkg",
    "slam": "slamwiki",
    "localization": "Localization",
    "mapping": "Mapping",
    "navigation": "Navigation",
    "pathplanning": "PathPlanning",
    "obstacle": "ObstacleDetection",
    "avoidance": "Avoidance",
    "mapping": "SimultaneousLocalizationAndMapping",
    "sensorfusion": "SensorFusion",
    "lidar": "LIDAR",
    "radar": "RADAR",
    "camera": "Camera",
    "stereo": "StereoVision",
    "depth": "DepthSensing",
    "thermal": "ThermalCamera",
    "sonar": "SONAR",
    "imu": "IMU",
    "gps": "GPS",
    "encoders": "Encoders",
    "odometry": "Odometry",
    "fusion": "SensorFusion",
    "kalman": "KalmanFilter",
    "ekf": "ExtendedKalmanFilter",
    "ukf": "UnscentedKalmanFilter",
    "pf": "ParticleFilter",
    "mbh": "ModelBasedPrediction",
    "lc": "LearningControl",
    "ad": "AutonomousDriving",
    "ads": "AutonomousDriving",
    "ad": "AutonomousDriving",
    "sdv": "SoftwareDefinedVehicle",
    "ev": "ElectricVehicle",
    "hev": "HybridElectricVehicle",
    "phev": "Plug-inHybridElectricVehicle",
    "bev": "BatteryElectricVehicle",
    "fcev": "FuelCellElectricVehicle",
    "av": "AutonomousVehicle",
    "v2x": "V2X",
    "v2v": "V2V",
    "v2i": "V2I",
    "v2p": "V2P",
    "v2n": "V2N",
    "v2g": "V2G",
    "c2c": "C2C",
    "c2i": "C2I",
    "ota": "OTA",
    "ot update": "OTA",
    "firmware": "Firmware",
    "bl": "Bootloader",
    "secureboot": "SecureBoot",
    "tz": "TrustedZone",
    "tee": "TEE",
    "se": "SecureElement",
    "hsm": "HSM",
    "kms": "KMS",
    "pki": "PKI",
    "ca": "CA",
    "ocsp": "OCSP",
    "crl": "CRL",
    "证书": "Certificate",
    "tls": "TLS",
    "ssl": "SSL",
    "https": "HTTPS",
    "http": "HTTP",
    "http2": "HTTP2",
    "http3": "HTTP3",
    "websocket": "WebSocket",
    "sse": "SSE",
    "grpc": "gRPC",
    "thrift": "Thrift",
    "avro": "Avro",
    "protobuf": "Protobuf",
    "msgpack": "MsgPack",
    "cbor": "CBOR",
    "jsonrpc": "JSON-RPC",
    "xmlrpc": "XML-RPC",
    "rest": "REST",
    "soap": "SOAP",
    "graphql": "GraphQL",
    "falcor": "Falcor",
    "odata": "OData",
    "jsonapi": "JSONAPI",
    "hateoas": "HATEOAS",
    "crud": "CRUD",
    "rest": "REST",
    "soap": "SOAP",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "websocket": "WebSocket",
    "sse": "SSE",
    "polling": "Polling",
    "webhook": "Webhook",
    "mqtt": "MQTT",
    "amqp": "AMQP",
    "stomp": "STOMP",
    "xmpp": "XMPP",
    "iamqp": "AMQP",
    "zeromq": "ZeroMQ",
    "nanomsg": "NanoMsg",
    "nng": "NNG",
    "ipc": "IPC",
    "unixsocket": "UnixSocket",
    "namedpipe": "NamedPipe",
    "sharedmemory": "SharedMemory",
    "mmap": "Mmap",
    "signal": "Signal",
    "queue": "Queue",
    "pipe": "Pipe",
    "socket": "Socket",
    "tcp": "TCP",
    "udp": "UDP",
    "unix": "Unix",
    "inet": "INET",
    "inet6": "INET6",
    "packet": "Packet",
    "frame": "Frame",
    "segment": "Segment",
    "datagram": "Datagram",
    "message": "Message",
    "stream": "Stream",
    "dgram": "Datagram",
    "seqpacket": "SeqPacket",
    "raw": "Raw",
    "cloexec": "CLOEXEC",
    "nonblock": "NONBLOCK",
    "blocking": "BLOCKING",
    "sync": "Synchronous",
    "async": "Asynchronous",
    "aio": "AsynchronousIO",
    "epoll": "epoll",
    "kqueue": "kqueue",
    "iocp": "IOCP",
    "poll": "poll",
    "select": "select",
    "react": "Reactor",
    "proactor": "Proactor",
    "coop": "Cooperative",
    "preemptive": "Preemptive",
    "thread": "Thread",
    "process": "Process",
    "coroutine": "Coroutine",
    "goroutine": "GoRoutine",
    "greenlet": "Greenlet",
    "fiber": "Fiber",
    "tasklet": "Tasklet",
    "actor": "Actor",
    "agent": "Agent",
    "spawn": "Spawn",
    "pool": "Pool",
    "executor": "Executor",
    "scheduler": "Scheduler",
    "workqueue": "WorkQueue",
    "threadpool": "ThreadPool",
    "processpool": "ProcessPool",
    "connectionpool": "ConnectionPool",
    "pool": "Pool",
    "pools": "Pools",
}


def _parse_domain(url_or_host: str) -> str:
    """Extract clean domain from URL or hostname."""
    url_or_host = url_or_host.strip().lower()
    # If it looks like a URL, parse it
    if "/" in url_or_host or "." not in url_or_host:
        parsed = urlparse(url_or_host if "://" in url_or_host else f"https://{url_or_host}")
        domain = parsed.netloc
    else:
        domain = url_or_host
    # Strip common prefixes
    if domain.startswith("www."):
        domain = domain[4:]
    return domain


def _keyword_to_domain(keyword: str) -> str | None:
    """Convert a keyword to a domain if it matches known topics."""
    kw = keyword.strip().lower()
    if kw in _TOPIC_TO_DOMAIN:
        return _TOPIC_TO_DOMAIN[kw]
    # If keyword itself looks like a domain (has dot), treat as domain
    if "." in kw and not kw.startswith("."):
        return kw
    return None


class InterestDomainMatcher:
    """
    Check if a domain matches any keyword in the interest graph.

    Keywords from the graph are mapped to domains via inference
    (topic → domain mapping) or by treating domain-shaped keywords as domains.
    """

    def __init__(self, vault_path: str | None = None):
        self._domains: set[str] = set()
        self._refresh(vault_path)

    def _refresh(self, vault_path: str | None = None):
        """Reload interest domains from graph."""
        try:
            interests = extract_interests(vault_path)
            domains: set[str] = set()
            for kw in interests:
                domain = _keyword_to_domain(kw)
                if domain:
                    domains.add(domain)
            self._domains = domains
            _logger.debug("InterestDomainMatcher: loaded %d domains from graph", len(domains))
        except Exception as e:
            _logger.warning("InterestDomainMatcher: failed to load interests: %s", e)
            self._domains = set()

    def is_interest_domain(self, domain: str) -> bool:
        """True if domain matches or is subdomain of an interest domain."""
        if not domain:
            return False
        clean = _parse_domain(domain)
        if not clean:
            return False
        # Exact match
        if clean in self._domains:
            return True
        # Subdomain match: raw.githubusercontent.com ends with .github.com
        for interest in self._domains:
            if clean.endswith("." + interest):
                return True
        return False

    def get_interest_domains(self) -> set[str]:
        """All interest domains derived from graph keywords."""
        return set(self._domains)
